[package]
name = "nu_plugin_nups2"
version = "0.104.0"
edition = "2021"

[features]
default = []

[dependencies]
nu-plugin = "0.104.0"
nu-protocol = "0.104.0"

[dependencies.nups2]
path = "../nups2"
default-features = false
features = ["fast", "manifests", "filename_scraper"]
